networks:
  soigineer_net:
    driver: bridge

volumes:
  redpanda_data:
  clickhouse_data:
  redis_data:

services:
  # ==========================================
  # REDPANDA BROKER
  # ==========================================
  redpanda-broker:
    image: docker.io/redpandadata/redpanda:v25.3.15
    container_name: redpanda-broker
    networks:
      - soigineer_net
    ports:
      - "${REDPANDA_EXTERNAL_PORT:-19092}:19092" # Port cho máy tính (Host) gọi vào Redpanda
      - "9644:9644" # Port quản trị Admin API
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    command:
      - redpanda
      - start
      - --mode=dev-container # Bật chế độ Dev: Tự động bỏ qua các giới hạn phần cứng khắt khe
      - --memory 2G
      - --smp 2
      # ĐỊNH NGHĨA CÁC CỔNG LẮNG NGHE (Lắng nghe ở đâu?)
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      # ĐỊNH NGHĨA ĐỊA CHỈ QUẢNG BÁ (Báo cho Client biết gọi vào đâu?)
      - --advertise-kafka-addr=internal://redpanda-broker:9092,external://localhost:19092

    healthcheck:
      test: ["CMD", "rpk", "cluster", "info", "--brokers", "127.0.0.1:9092"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  # ==========================================
  # REDPANDA CONSOLE
  # ==========================================
  redpanda-console:
    image: docker.io/redpandadata/console:v2.8.5
    container_name: redpanda-console
    restart: always
    networks:
      - soigineer_net
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKERS: "redpanda-broker:9092"
    depends_on:
      redpanda-broker:
        condition: service_healthy

  # ==========================================
  # TẠO TOPIC TỰ ĐỘNG
  # ==========================================
  redpanda-init:
    image: docker.io/redpandadata/redpanda:v25.3.15
    container_name: redpanda-topic-creator
    networks:
      - soigineer_net
    depends_on:
      redpanda-broker:
        condition: service_healthy
    # Chờ Redpanda khởi động xong, sau đó dùng CLI (rpk) để tạo topic
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        rpk topic create raw-logs --brokers redpanda-broker:9092 --partitions 6 --replicas 1 --topic-config retention.ms=259200000 || true
        rpk topic create alert --brokers redpanda-broker:9092 --partitions 3 --replicas 1 --topic-config retention.ms=259200000 || true
        rpk topic create processed-logs --brokers redpanda-broker:9092 --partitions 3 --replicas 1 --topic-config retention.ms=259200000 || true

  # ==========================================
  # INGESTION GATEWAY
  # ==========================================
  ingestion-gateway:
    build:
      context: ./backend
      dockerfile: internal/ingestion-gateway/Dockerfile
    container_name: ingestion-gateway
    networks:
      - soigineer_net
    ports:
      - "${GATEWAY_PORT:-8080}:8080"
    environment:
      GATEWAY_PORT: "${GATEWAY_PORT:-8080}"
      REDPANDA_BROKERS: redpanda-broker:9092
      REDPANDA_RAW_LOGS_TOPIC: "${REDPANDA_RAW_LOGS_TOPIC:-raw-logs}"
      REDPANDA_WRITER_BATCH_SIZE: "${REDPANDA_WRITER_BATCH_SIZE:-5000}"
      REDPANDA_WRITER_BATCH_TIMEOUT_MS: "${REDPANDA_WRITER_BATCH_TIMEOUT_MS:-30}"
      INGESTION_PRODUCER_TIMEOUT_MS: "${INGESTION_PRODUCER_TIMEOUT_MS:-10000}"
      GIN_MODE: "${GIN_MODE:-release}"
    depends_on:
      redpanda-init:
        condition: service_completed_successfully

  # ==========================================
  # CLICK HOUSE DB
  # ==========================================

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped
    networks:
      - soigineer_net

    ports:
      - "8123:8123"
      - "9000:9000"

    environment:
      CLICKHOUSE_DB: logs_db
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: secret123

    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./backend/deploy/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    deploy:
      resources:
        limits:
          memory: 3G

    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8123/ping",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

  # ==========================================
  # Processor
  # ==========================================
  logs-processor:
    build:
      context: ./backend
      dockerfile: internal/processing/Dockerfile
    #container_name: logs-processor
    networks:
      - soigineer_net
    environment:
      REDPANDA_BROKERS: "redpanda-broker:9092"
      REDPANDA_RAW_LOGS_TOPIC: "${REDPANDA_RAW_LOGS_TOPIC:-raw-logs}"
      REDPANDA_ALERT_TOPIC: "${REDPANDA_ALERT_TOPIC:-alert}"
      REDPANDA_PROCESSED_LOGS_TOPIC: "${REDPANDA_PROCESSED_LOGS_TOPIC:-processed-logs}"
      PROCESSOR_CONSUMER_GROUP: "${PROCESSOR_CONSUMER_GROUP:-process-raw-log}"
      PROCESSOR_BATCH_ROWS: "${PROCESSOR_BATCH_ROWS:-8000}"
      PROCESSOR_BATCH_BYTES: "${PROCESSOR_BATCH_BYTES:-25165824}"
      PROCESSOR_FLUSH_INTERVAL_MS: "${PROCESSOR_FLUSH_INTERVAL_MS:-1000}"
      PROCESSOR_MESSAGE_BUFFER: "${PROCESSOR_MESSAGE_BUFFER:-30000}"
      PROCESSOR_SAVE_TIMEOUT_MS: "${PROCESSOR_SAVE_TIMEOUT_MS:-20000}"
      PROCESSOR_ALERT_PRODUCER_TIMEOUT_MS: "${PROCESSOR_ALERT_PRODUCER_TIMEOUT_MS:-3000}"
      PROCESSOR_PROCESSED_LOG_PRODUCER_TIMEOUT_MS: "${PROCESSOR_PROCESSED_LOG_PRODUCER_TIMEOUT_MS:-3000}"
      PROCESSOR_SHUTDOWN_TIMEOUT_MS: "${PROCESSOR_SHUTDOWN_TIMEOUT_MS:-30000}"

      CLICKHOUSE_DB: "${CLICKHOUSE_DB:-logs_db}"
      CLICKHOUSE_USER: "${CLICKHOUSE_USER:-admin}"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD:-secret123}"
      CLICKHOUSE_HOST: "clickhouse"
      CLICKHOUSE_PORT: "${CLICKHOUSE_PORT:-9000}"
      CLICKHOUSE_MAX_OPEN_CONNS: "${CLICKHOUSE_MAX_OPEN_CONNS:-10}"
      CLICKHOUSE_MAX_IDLE_CONNS: "${CLICKHOUSE_MAX_IDLE_CONNS:-10}"
      CLICKHOUSE_CONN_MAX_LIFETIME_MINUTES: "${CLICKHOUSE_CONN_MAX_LIFETIME_MINUTES:-60}"

    depends_on:
      clickhouse:
        condition: service_healthy
      redpanda-init:
        condition: service_completed_successfully

  # ==========================================
  # REDIS - ALERT DEDUPLICATION
  # ==========================================
  redis:
    image: redis:8.0-alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - soigineer_net
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  # ==========================================
  # MONITORING SERVICE - WEBSOCKET + ALERT DISPATCHER
  # ==========================================
  monitoring-service:
    build:
      context: ./backend
      dockerfile: internal/monitoring/Dockerfile
    container_name: monitoring-service
    restart: unless-stopped
    networks:
      - soigineer_net
    ports:
      - "${MONITORING_PORT:-8090}:8090"
    env_file:
      - ./backend/.env
    environment:
      MONITORING_PORT: "${MONITORING_PORT:-8090}"
      REDPANDA_BROKERS: "redpanda-broker:9092"
      REDPANDA_PROCESSED_LOGS_TOPIC: "${REDPANDA_PROCESSED_LOGS_TOPIC:-processed-logs}"
      REALTIME_LOG_CONSUMER_GROUP: "${REALTIME_LOG_CONSUMER_GROUP:-realtime-log-viewer}"
      REDPANDA_ALERT_TOPIC: "${REDPANDA_ALERT_TOPIC:-alert}"
      ALERT_CONSUMER_GROUP: "${ALERT_CONSUMER_GROUP:-alert-dispatcher}"

      REDIS_ADDRESS: "redis:6379"
      ALERT_DEDUP_PERIOD: "${ALERT_DEDUP_PERIOD:-60}"

      TELEGRAM_TIMEOUT_MS: "${TELEGRAM_TIMEOUT_MS:-5000}"
    depends_on:
      redpanda-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
